### PR TITLE
4th Microverse Project: Building with Backgrounds and Gradients.

### PR DESCRIPTION
**Pull request by duducus**
The assignment for the project was to build a clone of an old version of Apple's website, linked here. The site looks simple enough at first sight, but I did run into a couple of complications trying to adjust the sizes of the containers to make the background images fit. The navbar section also looks deceptively simple, but it took a lot of work to make it look right, especially the last item to the right, which holds a search box.

### CODE REVIEW

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi @duducus, you have done really well with this project:+1:. Just a few changes are required:**
1. Your page has a horizontal scroll. Find which element or style is causing that and fix it.

2. Remove the underline in this section, it should only be underlined on hover.
image

3. Enable stickler for this repository.

4. Validate your html here https://validator.w3.org/#validate_by_upload

_**Kindly take care of the above and submit another code review request.**_

**Cheers:stars:**

**Comment by duducus** [comment]
I don't know what is the first point, can you plz explain that? that original page. The other stuff must be fixed.

**Review by euqueme — CHANGES_REQUESTED** [review]
> ### Pull Request under the review by Maria Eugenia Queme P. ( TSE )

### Hi @duducus  :wave: 

### Thank you for doing the changes requested by the previous reviewer, there are just a couple of things preventing the approval

## Apple logo

**Navbar**

- [ ] the first button should contain the apple logo

- Yours

image

- Original

image

## Activate Stickler

- [ ] The project can't be approved unless the last check has a green check :heavy_check_mark:  so if you haven't activated your repo on [stickler](https://stickler-ci.com/) 

image

### That's it! :raised_hands: 

### Please :pray: do the changes :memo: and submit back for a code review when you are done :rocket: 

Happy Coding! :woman_technologist: 

Any question? reach to me on slack **@ Maru**

PROJECT STATUS: REQUESTED CHANGES :vertical_traffic_light:

**Comment by majovanilla** [comment]
Code Review Request under review by Maria Reyes

**Comment by majovanilla** [comment]
Hey @duducus nice job implementing the changes requested by my colleagues! 

Everything looks good now, so your project is  **approved!**

**Pull request merged**
